"""
Relevant names for checks.
"""
from .address_menu import *

# All boss names
BOSS_MIKE_NAME = "Mike Goutokuji"
BOSS_MINORIKO_NAME = "Minoriko Aki"
BOSS_ETERNITY_NAME = "Eternity Larva"
BOSS_NEMUNO_NAME = "Nemuno Sakata"
BOSS_CIRNO_NAME = "Cirno"
BOSS_WAKASAGI_NAME = "Wakasagihime"
BOSS_SEKIBANKI_NAME = "Sekibanki"
BOSS_URUMI_NAME = "Urumi Ushizaki"
BOSS_EBISU_NAME = "Eika Ebisu"
BOSS_KUTAKA_NAME = "Kutaka Niwatari"
BOSS_NARUMI_NAME = "Narumi Yatadera"
BOSS_KOMACHI_NAME = "Komachi Onozuka"
BOSS_SANAE_NAME = "Sanae Kochiya"
BOSS_SAKUYA_NAME = "Sakuya Izayoi"
BOSS_YOUMU_NAME = "Youmu Konpaku"
BOSS_REIMU_NAME = "Reimu Hakurei"
BOSS_TSUKASA_NAME = "Tsukasa Kudamaki"
BOSS_MEGUMU_NAME = "Megumu Iizunamaru"
BOSS_CLOWNPIECE_NAME = "Clownpiece"
BOSS_TENSHI_NAME = "Tenshi Hinanawi"
BOSS_SUIKA_NAME = "Suika Ibuki"
BOSS_MAMIZOU_NAME = "Mamizou Futatsuiwa"
BOSS_SAKI_NAME = "Saki Kurokoma"
BOSS_MOMOYO_NAME = "Momoyo Himemushi"
BOSS_CHIMATA_NAME = "Chimata Tenkyuu"
BOSS_NITORI_NAME = "Nitori Kawashiro"
BOSS_TAKANE_NAME = "Takane Yamashiro"

# Boss IDs
BOSS_MIKE = 0
BOSS_MINORIKO = 1
BOSS_ETERNITY = 2
BOSS_NEMUNO = 3

BOSS_CIRNO = 4
BOSS_WAKASAGI = 5
BOSS_SEKIBANKI = 6
BOSS_URUMI = 7

BOSS_EBISU = 8
BOSS_KUTAKA = 9
BOSS_NARUMI = 10
BOSS_KOMACHI = 11

BOSS_SANAE = 12
BOSS_SAKUYA = 13
BOSS_YOUMU = 14
BOSS_REIMU = 15
BOSS_NITORI = 16

BOSS_TSUKASA = 17
BOSS_MEGUMU = 18
BOSS_CLOWNPIECE = 19
BOSS_TENSHI = 20

BOSS_SUIKA = 21
BOSS_MAMIZOU = 22
BOSS_SAKI = 23
BOSS_MOMOYO = 24
BOSS_TAKANE = 25

BOSS_CHIMATA = 26

# Boss stats ID
ENCOUNTER_ID = 0
ENCOUNTER_TYPE_NAME = "Encounter"
DEFEAT_ID = 1
DEFEAT_TYPE_NAME = "Defeat"

ALL_BOSSES_LIST = [
    [BOSS_MIKE_NAME],
    [BOSS_MIKE_NAME, BOSS_MINORIKO_NAME, BOSS_ETERNITY_NAME, BOSS_NEMUNO_NAME],
    [BOSS_CIRNO_NAME, BOSS_WAKASAGI_NAME, BOSS_SEKIBANKI_NAME, BOSS_URUMI_NAME],
    [BOSS_EBISU_NAME, BOSS_KUTAKA_NAME, BOSS_NARUMI_NAME, BOSS_KOMACHI_NAME],
    [BOSS_SANAE_NAME, BOSS_SAKUYA_NAME, BOSS_YOUMU_NAME, BOSS_REIMU_NAME, BOSS_NITORI_NAME],
    [BOSS_TSUKASA_NAME, BOSS_MEGUMU_NAME, BOSS_CLOWNPIECE_NAME, BOSS_TENSHI_NAME],
    [BOSS_SUIKA_NAME, BOSS_MAMIZOU_NAME, BOSS_SAKI_NAME, BOSS_MOMOYO_NAME, BOSS_TAKANE_NAME],
    [BOSS_CHIMATA_NAME]
]

STORY_BOSSES_LIST = [BOSS_NITORI_NAME, BOSS_TAKANE_NAME, BOSS_CHIMATA_NAME]

BOSS_NAME_TO_ID = {
    BOSS_MIKE_NAME: BOSS_MIKE,
    BOSS_MINORIKO_NAME: BOSS_MINORIKO,
    BOSS_ETERNITY_NAME: BOSS_ETERNITY,
    BOSS_NEMUNO_NAME: BOSS_NEMUNO,

    BOSS_CIRNO_NAME: BOSS_CIRNO,
    BOSS_WAKASAGI_NAME: BOSS_WAKASAGI,
    BOSS_SEKIBANKI_NAME: BOSS_SEKIBANKI,
    BOSS_URUMI_NAME: BOSS_URUMI,

    BOSS_EBISU_NAME: BOSS_EBISU,
    BOSS_KUTAKA_NAME: BOSS_KUTAKA,
    BOSS_NARUMI_NAME: BOSS_NARUMI,
    BOSS_KOMACHI_NAME: BOSS_KOMACHI,

    BOSS_SANAE_NAME: BOSS_SANAE,
    BOSS_SAKUYA_NAME: BOSS_SAKUYA,
    BOSS_YOUMU_NAME: BOSS_YOUMU,
    BOSS_REIMU_NAME: BOSS_REIMU,
    BOSS_NITORI_NAME: BOSS_NITORI,

    BOSS_TSUKASA_NAME: BOSS_TSUKASA,
    BOSS_MEGUMU_NAME: BOSS_MEGUMU,
    BOSS_CLOWNPIECE_NAME: BOSS_CLOWNPIECE,
    BOSS_TENSHI_NAME: BOSS_TENSHI,

    BOSS_SUIKA_NAME: BOSS_SUIKA,
    BOSS_MAMIZOU_NAME: BOSS_MAMIZOU,
    BOSS_SAKI_NAME: BOSS_SAKI,
    BOSS_MOMOYO_NAME: BOSS_MOMOYO,
    BOSS_TAKANE_NAME: BOSS_TAKANE,

    BOSS_CHIMATA_NAME: BOSS_CHIMATA
}

# Special progressive item name
# Having one is equivalent to having access to the Tutorial
PROGRESS_ITEM_NAME_FULL = "Progressive Market"

# Shortened stage names
TUTORIAL_NAME = "Tutorial"
STAGE1_NAME = "1st Market"
STAGE2_NAME = "2nd Market"
STAGE3_NAME = "3rd Market"
STAGE4_NAME = "4th Market"
STAGE5_NAME = "5th Market"
STAGE6_NAME = "6th Market"
ENDSTAGE_NAME = "End of Market"
CHALLENGE_NAME = "Challenge Market"

# Full stage names
TUTORIAL_NAME_FULL = f"{TUTORIAL_NAME} - First Black Market Deal"
STAGE1_NAME_FULL = f"{STAGE1_NAME} - Secret Heaven Cliff"
STAGE2_NAME_FULL = f"{STAGE2_NAME} - Misty Lake"
STAGE3_NAME_FULL = f"{STAGE3_NAME} - Sai no Kawara"
STAGE4_NAME_FULL = f"{STAGE4_NAME} - Moriya Shrine (Dark Fair)"
STAGE5_NAME_FULL = f"{STAGE5_NAME} - Youkai Mountain"
STAGE6_NAME_FULL = f"{STAGE6_NAME} - Rainbow Dragon Cave"
ENDSTAGE_NAME_FULL = f"{ENDSTAGE_NAME} - Lunar Rainbow Market"
CHALLENGE_NAME_FULL = f"{CHALLENGE_NAME} - Lunar Rainbow Black Market"

STAGE_NAME_LIST = [
    TUTORIAL_NAME_FULL, STAGE1_NAME_FULL, STAGE2_NAME_FULL,
    STAGE3_NAME_FULL, STAGE4_NAME_FULL, STAGE5_NAME_FULL,
    STAGE6_NAME_FULL, ENDSTAGE_NAME_FULL, CHALLENGE_NAME_FULL
]

STAGE_SHORT_TO_FULL_NAME = {
    TUTORIAL_NAME: TUTORIAL_NAME_FULL,
    STAGE1_NAME: STAGE1_NAME_FULL,
    STAGE2_NAME: STAGE2_NAME_FULL,
    STAGE3_NAME: STAGE3_NAME_FULL,
    STAGE4_NAME: STAGE4_NAME_FULL,
    STAGE5_NAME: STAGE5_NAME_FULL,
    STAGE6_NAME: STAGE6_NAME_FULL,
    ENDSTAGE_NAME: ENDSTAGE_NAME_FULL,
    CHALLENGE_NAME: CHALLENGE_NAME_FULL
}

STAGE_FULL_TO_SHORT_NAME = {
    TUTORIAL_NAME_FULL: TUTORIAL_NAME,
    STAGE1_NAME_FULL: STAGE1_NAME,
    STAGE2_NAME_FULL: STAGE2_NAME,
    STAGE3_NAME_FULL: STAGE3_NAME,
    STAGE4_NAME_FULL: STAGE4_NAME,
    STAGE5_NAME_FULL: STAGE5_NAME,
    STAGE6_NAME_FULL: STAGE6_NAME,
    ENDSTAGE_NAME_FULL: ENDSTAGE_NAME,
    CHALLENGE_NAME_FULL: CHALLENGE_NAME
}

# Miscellaneous region names
CARD_SHOP_NAME = "Permanent Card Shop"
CARD_DEX_NAME = "Ability Card Dex"
ENDSTAGE_CHOOSE_NAME = "Market Card Reward"

# Entrances to region names
ORIGIN_TO_TUTORIAL_NAME = f"Menu to {TUTORIAL_NAME}"
ORIGIN_TO_STAGE1_NAME = f"Menu to {STAGE1_NAME}"
ORIGIN_TO_STAGE2_NAME = f"Menu to {STAGE2_NAME}"
ORIGIN_TO_STAGE3_NAME = f"Menu to {STAGE3_NAME}"
ORIGIN_TO_STAGE4_NAME = f"Menu to {STAGE4_NAME}"
ORIGIN_TO_STAGE5_NAME = f"Menu to {STAGE5_NAME}"
ORIGIN_TO_STAGE6_NAME = f"Menu to {STAGE6_NAME}"
ORIGIN_TO_CHIMATA_NAME = f"Menu to {ENDSTAGE_NAME}"
ORIGIN_TO_CHALLENGE_NAME = f"Menu to {CHALLENGE_NAME}"
ORIGIN_TO_DEX_NAME = f"Menu to {CARD_DEX_NAME}"

ORIGIN_TO_REGION_DICT = {
    TUTORIAL_NAME: ORIGIN_TO_TUTORIAL_NAME,
    STAGE1_NAME: ORIGIN_TO_STAGE1_NAME,
    STAGE2_NAME: ORIGIN_TO_STAGE2_NAME,
    STAGE3_NAME: ORIGIN_TO_STAGE3_NAME,
    STAGE4_NAME: ORIGIN_TO_STAGE4_NAME,
    STAGE5_NAME: ORIGIN_TO_STAGE5_NAME,
    STAGE6_NAME: ORIGIN_TO_STAGE6_NAME,
    ENDSTAGE_NAME: ORIGIN_TO_CHIMATA_NAME,
    CHALLENGE_NAME: ORIGIN_TO_CHALLENGE_NAME,
    CARD_DEX_NAME: ORIGIN_TO_DEX_NAME
}

TUTORIAL_TO_CHOOSE_NAME = f"{TUTORIAL_NAME} to {ENDSTAGE_CHOOSE_NAME}"
STAGE1_TO_CHOOSE_NAME = f"{STAGE1_NAME} to {ENDSTAGE_CHOOSE_NAME}"
STAGE2_TO_CHOOSE_NAME = f"{STAGE2_NAME} to {ENDSTAGE_CHOOSE_NAME}"
STAGE3_TO_CHOOSE_NAME = f"{STAGE3_NAME} to {ENDSTAGE_CHOOSE_NAME}"
STAGE4_TO_CHOOSE_NAME = f"{STAGE4_NAME} to {ENDSTAGE_CHOOSE_NAME}"
STAGE5_TO_CHOOSE_NAME = f"{STAGE5_NAME} to {ENDSTAGE_CHOOSE_NAME}"
STAGE6_TO_CHOOSE_NAME = f"{STAGE6_NAME} to {ENDSTAGE_CHOOSE_NAME}"
CHIMATA_TO_CHOOSE_NAME = f"{ENDSTAGE_NAME} to {ENDSTAGE_CHOOSE_NAME}"
CHALLENGE_TO_CHOOSE_NAME = f"{CHALLENGE_NAME} to {ENDSTAGE_CHOOSE_NAME}"

STAGE_TO_CARD_REWARD_DICT = {
    TUTORIAL_NAME: TUTORIAL_TO_CHOOSE_NAME,
    STAGE1_NAME: STAGE1_TO_CHOOSE_NAME,
    STAGE2_NAME: STAGE2_TO_CHOOSE_NAME,
    STAGE3_NAME: STAGE3_TO_CHOOSE_NAME,
    STAGE4_NAME: STAGE4_TO_CHOOSE_NAME,
    STAGE5_NAME: STAGE5_TO_CHOOSE_NAME,
    STAGE6_NAME: STAGE6_TO_CHOOSE_NAME,
    ENDSTAGE_NAME: CHIMATA_TO_CHOOSE_NAME,
    CHALLENGE_NAME: CHALLENGE_TO_CHOOSE_NAME
}

STAGE_LIST = [
    TUTORIAL_NAME, STAGE1_NAME, STAGE2_NAME,
    STAGE3_NAME, STAGE4_NAME, STAGE5_NAME,
    STAGE6_NAME, ENDSTAGE_NAME, CHALLENGE_NAME
]

# Region list
REGION_LIST = STAGE_LIST + [CARD_DEX_NAME, ENDSTAGE_CHOOSE_NAME]

# Stage IDs
TUTORIAL_ID = 0
STAGE1_ID = 1
STAGE2_ID = 2
STAGE3_ID = 3
STAGE4_ID = 4
STAGE5_ID = 5
STAGE6_ID = 6
STAGE_CHIMATA_ID = 7
STAGE_CHALLENGE_ID = 8

# Stage ID ordered List.
STAGE_ID_LIST = [TUTORIAL_ID, STAGE1_ID, STAGE2_ID, STAGE3_ID, STAGE4_ID, STAGE5_ID, STAGE6_ID, STAGE_CHIMATA_ID, STAGE_CHALLENGE_ID]

# Stage IDs to Stage Name
STAGE_ID_TO_SHORT_NAME = {
    TUTORIAL_ID: TUTORIAL_NAME,
    STAGE1_ID: STAGE1_NAME,
    STAGE2_ID: STAGE2_NAME,
    STAGE3_ID: STAGE3_NAME,
    STAGE4_ID: STAGE4_NAME,
    STAGE5_ID: STAGE5_NAME,
    STAGE6_ID: STAGE6_NAME,
    STAGE_CHIMATA_ID: ENDSTAGE_NAME,
    STAGE_CHALLENGE_ID: CHALLENGE_NAME
}

# Stage Name to IDs
STAGE_NAME_TO_ID: dict[str, int] = {
    TUTORIAL_NAME: TUTORIAL_ID,
    STAGE1_NAME: STAGE1_ID,
    STAGE2_NAME: STAGE2_ID,
    STAGE3_NAME: STAGE3_ID,
    STAGE4_NAME: STAGE4_ID,
    STAGE5_NAME: STAGE5_ID,
    STAGE6_NAME: STAGE6_ID,
    ENDSTAGE_NAME: STAGE_CHIMATA_ID,
    CHALLENGE_NAME: STAGE_CHALLENGE_ID
}

ADDR_BOSS_ID_TO_PTR = {
    TUTORIAL_ID: {
        BOSS_MIKE: [
            ADDR_TUTORIAL_MIKE_ENCOUNTER,
            ADDR_TUTORIAL_MIKE_DEFEAT
        ]
    },
    STAGE1_ID: {
        BOSS_MIKE: [
            ADDR_STAGE1_MIKE_ENCOUNTER,
            ADDR_STAGE1_MIKE_DEFEAT
        ],
        BOSS_MINORIKO: [
            ADDR_STAGE1_MINORIKO_ENCOUNTER,
            ADDR_STAGE1_MINORIKO_DEFEAT
        ],
        BOSS_ETERNITY: [
            ADDR_STAGE1_ETERNITY_ENCOUNTER,
            ADDR_STAGE1_ETERNITY_DEFEAT
        ],
        BOSS_NEMUNO: [
            ADDR_STAGE1_NEMUNO_ENCOUNTER,
            ADDR_STAGE1_NEMUNO_DEFEAT
        ]
    },
    STAGE2_ID: {
        BOSS_CIRNO: [
            ADDR_STAGE2_CIRNO_ENCOUNTER,
            ADDR_STAGE2_CIRNO_DEFEAT
        ],
        BOSS_WAKASAGI: [
            ADDR_STAGE2_WAKASAGI_ENCOUNTER,
            ADDR_STAGE2_WAKASAGI_DEFEAT
        ],
        BOSS_SEKIBANKI: [
            ADDR_STAGE2_SEKIBANKI_ENCOUNTER,
            ADDR_STAGE2_SEKIBANKI_DEFEAT
        ],
        BOSS_URUMI: [
            ADDR_STAGE2_URUMI_ENCOUNTER,
            ADDR_STAGE2_URUMI_DEFEAT
        ]
    },
    STAGE3_ID: {
        BOSS_EBISU: [
            ADDR_STAGE3_EBISU_ENCOUNTER,
            ADDR_STAGE3_EBISU_DEFEAT
        ],
        BOSS_KUTAKA: [
            ADDR_STAGE3_KUTAKA_ENCOUNTER,
            ADDR_STAGE3_KUTAKA_DEFEAT
        ],
        BOSS_NARUMI: [
            ADDR_STAGE3_NARUMI_ENCOUNTER,
            ADDR_STAGE3_NARUMI_DEFEAT
        ],
        BOSS_KOMACHI: [
            ADDR_STAGE3_KOMACHI_ENCOUNTER,
            ADDR_STAGE3_KOMACHI_DEFEAT
        ]
    },
    STAGE4_ID: {
        BOSS_SANAE: [
            ADDR_STAGE4_SANAE_ENCOUNTER,
            ADDR_STAGE4_SANAE_DEFEAT
        ],
        BOSS_SAKUYA: [
            ADDR_STAGE4_SAKUYA_ENCOUNTER,
            ADDR_STAGE4_SAKUYA_DEFEAT
        ],
        BOSS_YOUMU: [
            ADDR_STAGE4_YOUMU_ENCOUNTER,
            ADDR_STAGE4_YOUMU_DEFEAT
        ],
        BOSS_REIMU: [
            ADDR_STAGE4_REIMU_ENCOUNTER,
            ADDR_STAGE4_REIMU_DEFEAT
        ],
        BOSS_NITORI: [
            ADDR_STORY_NITORI_ENCOUNTER,
            ADDR_STORY_NITORI_DEFEAT
        ]
    },
    STAGE5_ID: {
        BOSS_TSUKASA: [
            ADDR_STAGE5_TSUKASA_ENCOUNTER,
            ADDR_STAGE5_TSUKASA_DEFEAT
        ],
        BOSS_MEGUMU: [
            ADDR_STAGE5_MEGUMU_ENCOUNTER,
            ADDR_STAGE5_MEGUMU_DEFEAT
        ],
        BOSS_CLOWNPIECE: [
            ADDR_STAGE5_CLOWNPIECE_ENCOUNTER,
            ADDR_STAGE5_CLOWNPIECE_DEFEAT
        ],
        BOSS_TENSHI: [
            ADDR_STAGE5_TENSHI_ENCOUNTER,
            ADDR_STAGE5_TENSHI_DEFEAT
        ]
    },
    STAGE6_ID: {
        BOSS_SUIKA: [
            ADDR_STAGE6_SUIKA_ENCOUNTER,
            ADDR_STAGE6_SUIKA_DEFEAT
        ],
        BOSS_MAMIZOU: [
            ADDR_STAGE6_MAMIZOU_ENCOUNTER,
            ADDR_STAGE6_MAMIZOU_DEFEAT
        ],
        BOSS_SAKI: [
            ADDR_STAGE6_SAKI_ENCOUNTER,
            ADDR_STAGE6_SAKI_DEFEAT
        ],
        BOSS_MOMOYO: [
            ADDR_STAGE6_MOMOYO_ENCOUNTER,
            ADDR_STAGE6_MOMOYO_DEFEAT
        ],
        BOSS_TAKANE: [
            ADDR_STORY_TAKANE_ENCOUNTER,
            ADDR_STORY_TAKANE_DEFEAT
        ]
    },
    STAGE_CHIMATA_ID: {
        BOSS_CHIMATA: [
            ADDR_STORY_CHIMATA_ENCOUNTER,
            ADDR_STORY_CHIMATA_DEFEAT
        ]
    },
    STAGE_CHALLENGE_ID: {
        BOSS_MIKE: ADDR_CHALLENGE_MIKE_ENCOUNTER,
        BOSS_MINORIKO: ADDR_CHALLENGE_MINORIKO_ENCOUNTER,
        BOSS_ETERNITY: ADDR_CHALLENGE_ETERNITY_ENCOUNTER,
        BOSS_NEMUNO: ADDR_CHALLENGE_NEMUNO_ENCOUNTER,

        BOSS_CIRNO: ADDR_CHALLENGE_CIRNO_ENCOUNTER,
        BOSS_WAKASAGI: ADDR_CHALLENGE_WAKASAGI_ENCOUNTER,
        BOSS_SEKIBANKI: ADDR_CHALLENGE_SEKIBANKI_ENCOUNTER,
        BOSS_URUMI: ADDR_CHALLENGE_URUMI_ENCOUNTER,

        BOSS_EBISU: ADDR_CHALLENGE_EBISU_ENCOUNTER,
        BOSS_KUTAKA: ADDR_CHALLENGE_KUTAKA_ENCOUNTER,
        BOSS_NARUMI: ADDR_CHALLENGE_NARUMI_ENCOUNTER,
        BOSS_KOMACHI: ADDR_CHALLENGE_KOMACHI_ENCOUNTER,

        BOSS_SANAE: ADDR_CHALLENGE_SANAE_ENCOUNTER,
        BOSS_SAKUYA: ADDR_CHALLENGE_SAKUYA_ENCOUNTER,
        BOSS_YOUMU: ADDR_CHALLENGE_YOUMU_ENCOUNTER,
        BOSS_REIMU: ADDR_CHALLENGE_REIMU_ENCOUNTER,

        BOSS_TSUKASA: ADDR_CHALLENGE_TSUKASA_ENCOUNTER,
        BOSS_MEGUMU: ADDR_CHALLENGE_MEGUMU_ENCOUNTER,
        BOSS_CLOWNPIECE: ADDR_CHALLENGE_CLOWNPIECE_ENCOUNTER,
        BOSS_TENSHI: ADDR_CHALLENGE_TENSHI_ENCOUNTER,

        BOSS_SUIKA: ADDR_CHALLENGE_SUIKA_ENCOUNTER,
        BOSS_MAMIZOU: ADDR_CHALLENGE_MAMIZOU_ENCOUNTER,
        BOSS_SAKI: ADDR_CHALLENGE_SAKI_ENCOUNTER,
        BOSS_MOMOYO: ADDR_CHALLENGE_MOMOYO_ENCOUNTER
    }
}

ADDR_STAGE_ID_TO_PTR = {
    TUTORIAL_ID: ADDR_STAGE_TUTORIAL_UNLOCK,
    STAGE1_ID: ADDR_STAGE1_UNLOCK,
    STAGE2_ID: ADDR_STAGE2_UNLOCK,
    STAGE3_ID: ADDR_STAGE3_UNLOCK,
    STAGE4_ID: ADDR_STAGE4_UNLOCK,
    STAGE5_ID: ADDR_STAGE5_UNLOCK,
    STAGE6_ID: ADDR_STAGE6_UNLOCK,
    STAGE_CHIMATA_ID: ADDR_STAGE_CHIMATA_UNLOCK,
    STAGE_CHALLENGE_ID: ADDR_STAGE_CHALLENGE_UNLOCK
}