"""
Constant variables
"""
from .address_card_dex import *
from .address_card_shop import *
from .boss_and_stage import *

# Card IDs
BLANK_CARD = "CHIMATA"
NAZRIN_CARD_1 = "NAZRIN1"
NAZRIN_CARD_2 = "NAZRIN2"
LIFE_CARD = "LIFECARD"
RINGO_CARD = "RINGO"
MOKOU_CARD = "MOKOU"
REIMU_CARD_1 = "REIMU1"
REIMU_CARD_2 = "REIMU2"
MARISA_CARD_1 = "MARISA1"
MARISA_CARD_2 = "MARISA2"
SAKUYA_CARD_1 = "SAKUYA1"
SAKUYA_CARD_2 = "SAKUYA2"
SANAE_CARD_1 = "SANAE1"
SANAE_CARD_2 = "SANAE2"
YOUMU_CARD_1 = "YOUMU1"
YOUMU_CARD_2 = "YOUMU2"
ALICE_CARD = "ALICE"
CIRNO_CARD = "CIRNO"
OKINA_CARD = "OKINA"
UFO_CARD = "UFOCARD"
NITORI_CARD = "NITORI"
KANAKO_CARD = "KANAKO"
EIRIN_CARD = "EIRIN"
TEWI_CARD = "TEWI"
SAKI_BIGSHOT_CARD = "SAKI1"
BYAKUREN_CARD = "BYAKUREN"
KOISHI_CARD = "KOISHI"
SUWAKO_CARD = "SUWAKO"
AYA_CARD = "SPEEDQUEEN"
MAYUMI_CARD = "MAYUMI"
KAGUYA_CARD = "KAGUYA"
MAMIZOU_CARD = "MAMIZOU"
YUYUKO_CARD = "YUYUKO"
YACHIE_CARD = "YACHIE"
EIKI_CARD = "EIKI"
NARUMI_CARD = "NARUMI"
PATCHOULI_CARD = "PATCHOULI"
MIKE_CARD = "MIKE"
TAKANE_CARD = "TAKANE"
SANNYO_CARD = "SANNYO"
YUKARI_CARD = "YUKARI"
MALLET_CARD = "MALLET"
TENSHI_SHIELD_CARD = "TENSHI1"
TENSHI_THROW_CARD = "TENSHI2"
MOON_CARD = "MOON"
MIKO_CARD = "MIKO"
REMILIA_CARD = "REMILIA"
UTSUHO_CARD = "UTSUHO"
LILY_WHITE_CARD = "LILYWHITE"
RAIKO_CARD = "RAIKO"
SUMIREKO_CARD = "SUMIREKO"
MISUMARU_CARD = "MISUMARU"
TSUKASA_CARD = "TSUKASA"
MEGUMU_CARD = "MEGUMU"
MOMOYO_CARD = "MOMOYO"
TORAMARU_CARD = "TORAMARU"
STAR_SAPPHIRE_CARD = "STARSAPPHIRE"
LUNA_CHILD_CARD = "LUNACHILD"
SUNNY_MILK_CARD = "SUNNYMILK"
FLANDRE_CARD = "FLANDRE"
FUTO_CARD = "FUTO"
AUNN_CARD = "AUNN"
JOON_CARD = "JOON"
SHION_CARD = "SHION"
KEIKI_CARD = "KEIKI"
SEIRAN_CARD = "SEIRAN"
DOREMY_CARD = "DOREMY"
JUNKO_CARD = "JUNKO"
NITORI_STORY_CARD = "NITORISTORY"
TAKANE_STORY_CARD = "TAKANESTORY"
MINORIKO_CARD = "MINORIKO"
ETERNITY_CARD = "ETERNITY"
NEMUNO_CARD = "NEMUNO"
WAKASAGI_CARD = "WAKASAGI"
SEKIBANKI_CARD = "SEKIBANKI"
URUMI_CARD = "URUMI"
KUTAKA_CARD = "KUTAKA"
KOMACHI_CARD = "KOMACHI"
EBISU_CARD = "EBISU"
SEIJA_CARD = "SEIJA"
CLOWNPIECE_CARD = "CLOWN"
SAKI_POWER_CARD = "SAKI2"
SUIKA_CARD = "SUIKA"
TEACUP_REIMU_CARD = "TEACUP1"
TEACUP_MARISA_CARD = "TEACUP2"

# Card ID to Card Shop Addresses
# Nazrin's cards are not sold in shop.
ADDR_CARD_TO_SHOP = {
    BLANK_CARD: ADDR_SHOP_BLANK_CARD,
    NAZRIN_CARD_1: 0x00000000,
    NAZRIN_CARD_2: 0x00000000,
    LIFE_CARD: ADDR_SHOP_LIFE_CARD,
    RINGO_CARD: ADDR_SHOP_RINGO_CARD,
    MOKOU_CARD: ADDR_SHOP_MOKOU_CARD,
    REIMU_CARD_1: ADDR_SHOP_REIMU_1,
    REIMU_CARD_2: ADDR_SHOP_REIMU_2,
    MARISA_CARD_1: ADDR_SHOP_MARISA_1,
    MARISA_CARD_2: ADDR_SHOP_MARISA_2,
    SAKUYA_CARD_1: ADDR_SHOP_SAKUYA_1,
    SAKUYA_CARD_2: ADDR_SHOP_SAKUYA_2,
    SANAE_CARD_1: ADDR_SHOP_SANAE_1,
    SANAE_CARD_2: ADDR_SHOP_SANAE_2,
    YOUMU_CARD_1: ADDR_SHOP_YOUMU_1,
    YOUMU_CARD_2: ADDR_SHOP_YOUMU_2,
    ALICE_CARD: ADDR_SHOP_ALICE_CARD,
    CIRNO_CARD: ADDR_SHOP_CIRNO_CARD,
    OKINA_CARD: ADDR_SHOP_OKINA_CARD,
    UFO_CARD: ADDR_SHOP_UFO_CARD,
    NITORI_CARD: ADDR_SHOP_NITORI_CARD,
    KANAKO_CARD: ADDR_SHOP_KANAKO_CARD,
    EIRIN_CARD: ADDR_SHOP_EIRIN_CARD,
    TEWI_CARD: ADDR_SHOP_TEWI_CARD,
    SAKI_BIGSHOT_CARD: ADDR_SHOP_SAKI_BIGSHOT_CARD,
    SAKI_POWER_CARD: ADDR_SHOP_SAKI_POWER_CARD,
    BYAKUREN_CARD: ADDR_SHOP_BYAKUREN_CARD,
    KOISHI_CARD: ADDR_SHOP_KOISHI_CARD,
    SUWAKO_CARD: ADDR_SHOP_SUWAKO_CARD,
    AYA_CARD: ADDR_SHOP_AYA_CARD,
    MAYUMI_CARD: ADDR_SHOP_MAYUMI_CARD,
    KAGUYA_CARD: ADDR_SHOP_KAGUYA_CARD,
    MAMIZOU_CARD: ADDR_SHOP_MAMIZOU_CARD,
    YUYUKO_CARD: ADDR_SHOP_YUYUKO_CARD,
    YACHIE_CARD: ADDR_SHOP_YACHIE_CARD,
    EIKI_CARD: ADDR_SHOP_EIKI_CARD,
    NARUMI_CARD: ADDR_SHOP_NARUMI_CARD,
    PATCHOULI_CARD: ADDR_SHOP_PATCHOULI_CARD,
    MIKE_CARD: ADDR_SHOP_MIKE_CARD,
    TAKANE_CARD: ADDR_SHOP_TAKANE_CARD,
    SANNYO_CARD: ADDR_SHOP_SANNYO_CARD,
    YUKARI_CARD: ADDR_SHOP_YUKARI_CARD,
    MALLET_CARD: ADDR_SHOP_MALLET_CARD,
    TENSHI_SHIELD_CARD: ADDR_SHOP_TENSHI_SHIELD,
    TENSHI_THROW_CARD: ADDR_SHOP_TENSHI_THROW,
    MOON_CARD: ADDR_SHOP_MOON_CARD,
    MIKO_CARD: ADDR_SHOP_MIKO_CARD,
    REMILIA_CARD: ADDR_SHOP_REMILIA_CARD,
    UTSUHO_CARD: ADDR_SHOP_UTSUHO_CARD,
    LILY_WHITE_CARD: ADDR_SHOP_LILY_WHITE,
    RAIKO_CARD: ADDR_SHOP_RAIKO_CARD,
    SUMIREKO_CARD: ADDR_SHOP_SUMIREKO_CARD,
    MISUMARU_CARD: ADDR_SHOP_MISUMARU_CARD,
    TSUKASA_CARD: ADDR_SHOP_TSUKASA_CARD,
    MEGUMU_CARD: ADDR_SHOP_MEGUMU_CARD,
    MOMOYO_CARD: ADDR_SHOP_MOMOYO_CARD,
    TORAMARU_CARD: ADDR_SHOP_TORAMARU_CARD,
    STAR_SAPPHIRE_CARD: ADDR_SHOP_STAR_SAPPHIRE,
    LUNA_CHILD_CARD: ADDR_SHOP_LUNA_CHILD,
    SUNNY_MILK_CARD: ADDR_SHOP_SUNNY_MILK,
    FLANDRE_CARD: ADDR_SHOP_FLANDRE_CARD,
    FUTO_CARD: ADDR_SHOP_FUTO_CARD,
    AUNN_CARD: ADDR_SHOP_AUNN_CARD,
    JOON_CARD: ADDR_SHOP_JOON_CARD,
    SHION_CARD: ADDR_SHOP_SHION_CARD,
    KEIKI_CARD: ADDR_SHOP_KEIKI_CARD,
    SEIRAN_CARD: ADDR_SHOP_SEIRAN_CARD,
    DOREMY_CARD: ADDR_SHOP_DOREMY_CARD,
    JUNKO_CARD: ADDR_SHOP_JUNKO_CARD,
    NITORI_STORY_CARD: ADDR_SHOP_NITORI_STORY,
    TAKANE_STORY_CARD: ADDR_SHOP_TAKANE_STORY,
    MINORIKO_CARD: ADDR_SHOP_MINORIKO_CARD,
    ETERNITY_CARD: ADDR_SHOP_ETERNITY_CARD,
    NEMUNO_CARD: ADDR_SHOP_NEMUNO_CARD,
    WAKASAGI_CARD: ADDR_SHOP_WAKASAGI_CARD,
    URUMI_CARD: ADDR_SHOP_URUMI_CARD,
    KUTAKA_CARD: ADDR_SHOP_KUTAKA_CARD,
    KOMACHI_CARD: ADDR_SHOP_KOMACHI_CARD,
    EBISU_CARD: ADDR_SHOP_EBISU_CARD,
    SEIJA_CARD: ADDR_SHOP_SEIJA_CARD,
    CLOWNPIECE_CARD: ADDR_SHOP_CLOWNPIECE_CARD,
    SUIKA_CARD: ADDR_SHOP_SUIKA_CARD,
    TEACUP_REIMU_CARD: ADDR_SHOP_TEACUP_REIMU,
    TEACUP_MARISA_CARD: ADDR_SHOP_TEACUP_MARISA,
    SEKIBANKI_CARD: ADDR_SHOP_SEKIBANKI_CARD,
}

# Card ID to Card Dex Addresses
ADDR_CARD_TO_DEX = {
    BLANK_CARD: ADDR_DEX_BLANK_CARD,
    NAZRIN_CARD_1: ADDR_DEX_NAZRIN_1,
    NAZRIN_CARD_2: ADDR_DEX_NAZRIN_2,
    LIFE_CARD: ADDR_DEX_LIFE_CARD,
    RINGO_CARD: ADDR_DEX_RINGO_CARD,
    MOKOU_CARD: ADDR_DEX_MOKOU_CARD,
    REIMU_CARD_1: ADDR_DEX_REIMU_1,
    REIMU_CARD_2: ADDR_DEX_REIMU_2,
    MARISA_CARD_1: ADDR_DEX_MARISA_1,
    MARISA_CARD_2: ADDR_DEX_MARISA_2,
    SAKUYA_CARD_1: ADDR_DEX_SAKUYA_1,
    SAKUYA_CARD_2: ADDR_DEX_SAKUYA_2,
    SANAE_CARD_1: ADDR_DEX_SANAE_1,
    SANAE_CARD_2: ADDR_DEX_SANAE_2,
    YOUMU_CARD_1: ADDR_DEX_YOUMU_1,
    YOUMU_CARD_2: ADDR_DEX_YOUMU_2,
    ALICE_CARD: ADDR_DEX_ALICE_CARD,
    CIRNO_CARD: ADDR_DEX_CIRNO_CARD,
    OKINA_CARD: ADDR_DEX_OKINA_CARD,
    UFO_CARD: ADDR_DEX_UFO_CARD,
    NITORI_CARD: ADDR_DEX_NITORI_CARD,
    KANAKO_CARD: ADDR_DEX_KANAKO_CARD,
    EIRIN_CARD: ADDR_DEX_EIRIN_CARD,
    TEWI_CARD: ADDR_DEX_TEWI_CARD,
    SAKI_BIGSHOT_CARD: ADDR_DEX_SAKI_BIGSHOT_CARD,
    SAKI_POWER_CARD: ADDR_DEX_SAKI_POWER_CARD,
    BYAKUREN_CARD: ADDR_DEX_BYAKUREN_CARD,
    KOISHI_CARD: ADDR_DEX_KOISHI_CARD,
    SUWAKO_CARD: ADDR_DEX_SUWAKO_CARD,
    AYA_CARD: ADDR_DEX_AYA_CARD,
    MAYUMI_CARD: ADDR_DEX_MAYUMI_CARD,
    KAGUYA_CARD: ADDR_DEX_KAGUYA_CARD,
    MAMIZOU_CARD: ADDR_DEX_MAMIZOU_CARD,
    YUYUKO_CARD: ADDR_DEX_YUYUKO_CARD,
    YACHIE_CARD: ADDR_DEX_YACHIE_CARD,
    EIKI_CARD: ADDR_DEX_EIKI_CARD,
    NARUMI_CARD: ADDR_DEX_NARUMI_CARD,
    PATCHOULI_CARD: ADDR_DEX_PATCHOULI_CARD,
    MIKE_CARD: ADDR_DEX_MIKE_CARD,
    TAKANE_CARD: ADDR_DEX_TAKANE_CARD,
    SANNYO_CARD: ADDR_DEX_SANNYO_CARD,
    YUKARI_CARD: ADDR_DEX_YUKARI_CARD,
    MALLET_CARD: ADDR_DEX_MALLET_CARD,
    TENSHI_SHIELD_CARD: ADDR_DEX_TENSHI_SHIELD,
    TENSHI_THROW_CARD: ADDR_DEX_TENSHI_THROW,
    MOON_CARD: ADDR_DEX_MOON_CARD,
    MIKO_CARD: ADDR_DEX_MIKO_CARD,
    REMILIA_CARD: ADDR_DEX_REMILIA_CARD,
    UTSUHO_CARD: ADDR_DEX_UTSUHO_CARD,
    LILY_WHITE_CARD: ADDR_DEX_LILY_WHITE,
    RAIKO_CARD: ADDR_DEX_RAIKO_CARD,
    SUMIREKO_CARD: ADDR_DEX_SUMIREKO_CARD,
    MISUMARU_CARD: ADDR_DEX_MISUMARU_CARD,
    TSUKASA_CARD: ADDR_DEX_TSUKASA_CARD,
    MEGUMU_CARD: ADDR_DEX_MEGUMU_CARD,
    MOMOYO_CARD: ADDR_DEX_MOMOYO_CARD,
    TORAMARU_CARD: ADDR_DEX_TORAMARU_CARD,
    STAR_SAPPHIRE_CARD: ADDR_DEX_STAR_SAPPHIRE,
    LUNA_CHILD_CARD: ADDR_DEX_LUNA_CHILD,
    SUNNY_MILK_CARD: ADDR_DEX_SUNNY_MILK,
    FLANDRE_CARD: ADDR_DEX_FLANDRE_CARD,
    FUTO_CARD: ADDR_DEX_FUTO_CARD,
    AUNN_CARD: ADDR_DEX_AUNN_CARD,
    JOON_CARD: ADDR_DEX_JOON_CARD,
    SHION_CARD: ADDR_DEX_SHION_CARD,
    KEIKI_CARD: ADDR_DEX_KEIKI_CARD,
    SEIRAN_CARD: ADDR_DEX_SEIRAN_CARD,
    DOREMY_CARD: ADDR_DEX_DOREMY_CARD,
    JUNKO_CARD: ADDR_DEX_JUNKO_CARD,
    NITORI_STORY_CARD: ADDR_DEX_NITORI_STORY,
    TAKANE_STORY_CARD: ADDR_DEX_TAKANE_STORY,
    MINORIKO_CARD: ADDR_DEX_MINORIKO_CARD,
    ETERNITY_CARD: ADDR_DEX_ETERNITY_CARD,
    NEMUNO_CARD: ADDR_DEX_NEMUNO_CARD,
    WAKASAGI_CARD: ADDR_DEX_WAKASAGI_CARD,
    URUMI_CARD: ADDR_DEX_URUMI_CARD,
    KUTAKA_CARD: ADDR_DEX_KUTAKA_CARD,
    KOMACHI_CARD: ADDR_DEX_KOMACHI_CARD,
    EBISU_CARD: ADDR_DEX_EBISU_CARD,
    SEIJA_CARD: ADDR_DEX_SEIJA_CARD,
    CLOWNPIECE_CARD: ADDR_DEX_CLOWNPIECE_CARD,
    SUIKA_CARD: ADDR_DEX_SUIKA_CARD,
    TEACUP_REIMU_CARD: ADDR_DEX_TEACUP_REIMU,
    TEACUP_MARISA_CARD: ADDR_DEX_TEACUP_MARISA,
    SEKIBANKI_CARD: ADDR_DEX_SEKIBANKI_CARD
}

ABILITY_CARD_LIST = [
    BLANK_CARD, NAZRIN_CARD_1, NAZRIN_CARD_2, LIFE_CARD, RINGO_CARD,
    MOKOU_CARD, REIMU_CARD_1, REIMU_CARD_2, MARISA_CARD_1, MARISA_CARD_2,
    SAKUYA_CARD_1, SAKUYA_CARD_2, SANAE_CARD_1, SANAE_CARD_2, YOUMU_CARD_1,
    YOUMU_CARD_2, CIRNO_CARD, OKINA_CARD, UFO_CARD, NITORI_CARD,
    KANAKO_CARD, EIRIN_CARD, TEWI_CARD, SAKI_BIGSHOT_CARD, SAKI_POWER_CARD,
    BYAKUREN_CARD, KOISHI_CARD, SUWAKO_CARD, AYA_CARD, MAYUMI_CARD,
    KAGUYA_CARD, MAMIZOU_CARD, YUYUKO_CARD, YACHIE_CARD, EIKI_CARD,
    NARUMI_CARD, PATCHOULI_CARD, MIKE_CARD, TAKANE_CARD, SANNYO_CARD,
    YUKARI_CARD, MALLET_CARD, TENSHI_SHIELD_CARD, TENSHI_THROW_CARD, MOON_CARD,
    MIKO_CARD, REMILIA_CARD, UTSUHO_CARD, LILY_WHITE_CARD, RAIKO_CARD,
    SUMIREKO_CARD, MISUMARU_CARD, TSUKASA_CARD, MEGUMU_CARD, MOMOYO_CARD,
    TORAMARU_CARD, STAR_SAPPHIRE_CARD, LUNA_CHILD_CARD, SUNNY_MILK_CARD, FLANDRE_CARD,
    FUTO_CARD, AUNN_CARD, JOON_CARD, SHION_CARD, KEIKI_CARD,
    SEIRAN_CARD, DOREMY_CARD, JUNKO_CARD, NITORI_STORY_CARD, TAKANE_STORY_CARD,
    MINORIKO_CARD, ETERNITY_CARD, NEMUNO_CARD, WAKASAGI_CARD, URUMI_CARD,
    KUTAKA_CARD, KOMACHI_CARD, EBISU_CARD, SEIJA_CARD, CLOWNPIECE_CARD,
    SUIKA_CARD, TEACUP_REIMU_CARD, TEACUP_MARISA_CARD, SEKIBANKI_CARD, ALICE_CARD
]

# Card Names
BLANK_CARD_NAME = "Blank Card"
NAZRIN_CARD_1_NAME = "Money Comes and Goes On its Own (Funds)"
NAZRIN_CARD_2_NAME = "Money Comes and Goes On its Own (Bullet Money)"
LIFE_CARD_NAME = "Life Card"
RINGO_CARD_NAME = "Ringo-Brand Dango"
MOKOU_CARD_NAME = "Phoenix's Tail"
REIMU_CARD_1_NAME = "Yin-Yang Orb"
REIMU_CARD_2_NAME = "Yin-Yang Orb (Needle)"
MARISA_CARD_1_NAME = "Mini-Hakkero"
MARISA_CARD_2_NAME = "Mini-Hakkero (Missile)"
SAKUYA_CARD_1_NAME = "Maid Knife"
SAKUYA_CARD_2_NAME = "Maid Knife (Ricochet)"
SANAE_CARD_1_NAME = "Safe Return Amulet"
SANAE_CARD_2_NAME = "Shed Snakeskin Amulet"
YOUMU_CARD_1_NAME = "Half of a Half-Ghost"
YOUMU_CARD_2_NAME = "Half-Ghost's Spare Part"
ALICE_CARD_NAME = "Shanghai Doll"
CIRNO_CARD_NAME = "Ice Fairy"
OKINA_CARD_NAME = "Back Door"
UFO_CARD_NAME = "Annoying UFO"
NITORI_CARD_NAME = "Miser's Advice"
KANAKO_CARD_NAME = "Offerings to the Mountain God"
EIRIN_CARD_NAME = "Life Explosion Elixir"
TEWI_CARD_NAME = "Fraudster's Rabbit Foot"
SAKI_BIGSHOT_CARD_NAME = "Law of the Survival of the Fittest"
BYAKUREN_CARD_NAME = "Sutra of Dharmatic Power"
KOISHI_CARD_NAME = "Pebble Hat"
SUWAKO_CARD_NAME = "Bursting Red Frog"
AYA_CARD_NAME = "Gale Geta"
MAYUMI_CARD_NAME = "Idol Defense Corps"
KAGUYA_CARD_NAME = "Princess Kaguya's Secret Stash"
MAMIZOU_CARD_NAME = "Reliable Tanuki Apprentice"
YUYUKO_CARD_NAME = "Danmaku Ghost"
YACHIE_CARD_NAME = "Kiketsu Matriarch's Threat"
EIKI_CARD_NAME = "Money is the Best Lawyer in Hell"
NARUMI_CARD_NAME = "Physical Enhancement Jizo"
PATCHOULI_CARD_NAME = "Magician's Basic Study"
MIKE_CARD_NAME = "Maneki-neko with Good Business Skills"
TAKANE_CARD_NAME = "Yamawaro Shopping Technique"
SANNYO_CARD_NAME = "Dragon Pipe"
YUKARI_CARD_NAME = "Screen Border"
MALLET_CARD_NAME = "Miracle Mallet"
TENSHI_SHIELD_CARD_NAME = "Keystone of Endurance"
TENSHI_THROW_CARD_NAME = "Keystone Missile"
MOON_CARD_NAME = "Moon of Madness"
MIKO_CARD_NAME = "Esteemed Authority"
REMILIA_CARD_NAME = "Vampire Fang"
UTSUHO_CARD_NAME = "Subterranean Sun"
LILY_WHITE_CARD_NAME = "Item Season"
RAIKO_CARD_NAME = "Heavy Bass Drum"
SUMIREKO_CARD_NAME = "Psychokinesis"
MISUMARU_CARD_NAME = "Ancient Magatama"
TSUKASA_CARD_NAME = "Spirit Power Sample Bottle"
MEGUMU_CARD_NAME = "Great Tengu's Barley Rice"
MOMOYO_CARD_NAME = "Gluttonous Centipede"
TORAMARU_CARD_NAME = "Offensive Jeweled Pagoda"
STAR_SAPPHIRE_CARD_NAME = "Quiet Twinkling"
LUNA_CHILD_CARD_NAME = "Lunatic Stillness"
SUNNY_MILK_CARD_NAME = "Exuberant Powerlessness"
FLANDRE_CARD_NAME = "Aesthetics of Destruction"
FUTO_CARD_NAME = "Dragon's Passage"
AUNN_CARD_NAME = "Unleash the Guardian Hounds"
JOON_CARD_NAME = "Irresistible Feathered Fan"
SHION_CARD_NAME = "Soot-covered Uchiwa"
KEIKI_CARD_NAME = "No Problem for a Creator!"
SEIRAN_CARD_NAME = "The Rabbit That Landed"
DOREMY_CARD_NAME = "Sheep You Want to Count"
JUNKO_CARD_NAME = "Pristine Self-Confidence"
NITORI_STORY_CARD_NAME = "Capitalist's Dilemma"
TAKANE_STORY_CARD_NAME = "Hundredth Black Market"
MINORIKO_CARD_NAME = "Bumper Crop of Life"
ETERNITY_CARD_NAME = "Stimulating Scales"
NEMUNO_CARD_NAME = "Yamanba's Kitchen Knife"
WAKASAGI_CARD_NAME = "Smelt's Scales"
SEKIBANKI_CARD_NAME = "Freewheeling Severed Head"
URUMI_CARD_NAME = "Drenched Giant Snake"
KUTAKA_CARD_NAME = "Too-Honest Signpost"
KOMACHI_CARD_NAME = "Hasty Detour of the Three Crossings"
EBISU_CARD_NAME = "Laid-Back Invertebrate"
SEIJA_CARD_NAME = "Nimble Fabric"
CLOWNPIECE_CARD_NAME = "Life-Burning Torch"
SAKI_POWER_CARD_NAME = "Indominable Meathead"
SUIKA_CARD_NAME = "Drunkenly Whimsical Ibuki Gourd"
TEACUP_REIMU_CARD_NAME = "Teacup Reimu"
TEACUP_MARISA_CARD_NAME = "Teacup Marisa"

NEW_CARD = 0x80
OWNED_CARD = 0x01

# Card String ID to Name
CARD_ID_TO_NAME = {
    BLANK_CARD: BLANK_CARD_NAME,
    NAZRIN_CARD_1: NAZRIN_CARD_1_NAME,
    NAZRIN_CARD_2: NAZRIN_CARD_2_NAME,
    LIFE_CARD: LIFE_CARD_NAME,
    RINGO_CARD: RINGO_CARD_NAME,
    MOKOU_CARD: MOKOU_CARD_NAME,
    REIMU_CARD_1: REIMU_CARD_1_NAME,
    REIMU_CARD_2: REIMU_CARD_2_NAME,
    MARISA_CARD_1: MARISA_CARD_1_NAME,
    MARISA_CARD_2: MARISA_CARD_2_NAME,
    SAKUYA_CARD_1: SAKUYA_CARD_1_NAME,
    SAKUYA_CARD_2: SAKUYA_CARD_2_NAME,
    SANAE_CARD_1: SANAE_CARD_1_NAME,
    SANAE_CARD_2: SANAE_CARD_2_NAME,
    YOUMU_CARD_1: YOUMU_CARD_1_NAME,
    YOUMU_CARD_2: YOUMU_CARD_2_NAME,
    ALICE_CARD: ALICE_CARD_NAME,
    CIRNO_CARD: CIRNO_CARD_NAME,
    OKINA_CARD: OKINA_CARD_NAME,
    UFO_CARD: UFO_CARD_NAME,
    NITORI_CARD: NITORI_CARD_NAME,
    KANAKO_CARD: KANAKO_CARD_NAME,
    EIRIN_CARD: EIRIN_CARD_NAME,
    TEWI_CARD: TEWI_CARD_NAME,
    SAKI_BIGSHOT_CARD: SAKI_BIGSHOT_CARD_NAME,
    SAKI_POWER_CARD: SAKI_POWER_CARD_NAME,
    BYAKUREN_CARD: BYAKUREN_CARD_NAME,
    KOISHI_CARD: KOISHI_CARD_NAME,
    SUWAKO_CARD: SUWAKO_CARD_NAME,
    AYA_CARD: AYA_CARD_NAME,
    MAYUMI_CARD: MAYUMI_CARD_NAME,
    KAGUYA_CARD: KAGUYA_CARD_NAME,
    MAMIZOU_CARD: MAMIZOU_CARD_NAME,
    YUYUKO_CARD: YUYUKO_CARD_NAME,
    YACHIE_CARD: YACHIE_CARD_NAME,
    EIKI_CARD: EIKI_CARD_NAME,
    NARUMI_CARD: NARUMI_CARD_NAME,
    PATCHOULI_CARD: PATCHOULI_CARD_NAME,
    MIKE_CARD: MIKE_CARD_NAME,
    TAKANE_CARD: TAKANE_CARD_NAME,
    SANNYO_CARD: SANNYO_CARD_NAME,
    YUKARI_CARD: YUKARI_CARD_NAME,
    MALLET_CARD: MALLET_CARD_NAME,
    TENSHI_SHIELD_CARD: TENSHI_SHIELD_CARD_NAME,
    TENSHI_THROW_CARD: TENSHI_THROW_CARD_NAME,
    MOON_CARD: MOON_CARD_NAME,
    MIKO_CARD: MIKO_CARD_NAME,
    REMILIA_CARD: REMILIA_CARD_NAME,
    UTSUHO_CARD: UTSUHO_CARD_NAME,
    LILY_WHITE_CARD: LILY_WHITE_CARD_NAME,
    RAIKO_CARD: RAIKO_CARD_NAME,
    SUMIREKO_CARD: SUMIREKO_CARD_NAME,
    MISUMARU_CARD: MISUMARU_CARD_NAME,
    TSUKASA_CARD: TSUKASA_CARD_NAME,
    MEGUMU_CARD: MEGUMU_CARD_NAME,
    MOMOYO_CARD: MOMOYO_CARD_NAME,
    TORAMARU_CARD: TORAMARU_CARD_NAME,
    STAR_SAPPHIRE_CARD: STAR_SAPPHIRE_CARD_NAME,
    LUNA_CHILD_CARD: LUNA_CHILD_CARD_NAME,
    SUNNY_MILK_CARD: SUNNY_MILK_CARD_NAME,
    FLANDRE_CARD: FLANDRE_CARD_NAME,
    FUTO_CARD: FUTO_CARD_NAME,
    AUNN_CARD: AUNN_CARD_NAME,
    JOON_CARD: JOON_CARD_NAME,
    SHION_CARD: SHION_CARD_NAME,
    KEIKI_CARD: KEIKI_CARD_NAME,
    SEIRAN_CARD: SEIRAN_CARD_NAME,
    DOREMY_CARD: DOREMY_CARD_NAME,
    JUNKO_CARD: JUNKO_CARD_NAME,
    NITORI_STORY_CARD: NITORI_STORY_CARD_NAME,
    TAKANE_STORY_CARD: TAKANE_STORY_CARD_NAME,
    MINORIKO_CARD: MINORIKO_CARD_NAME,
    ETERNITY_CARD: ETERNITY_CARD_NAME,
    NEMUNO_CARD: NEMUNO_CARD_NAME,
    WAKASAGI_CARD: WAKASAGI_CARD_NAME,
    SEKIBANKI_CARD: SEKIBANKI_CARD_NAME,
    URUMI_CARD: URUMI_CARD_NAME,
    KUTAKA_CARD: KUTAKA_CARD_NAME,
    KOMACHI_CARD: KOMACHI_CARD_NAME,
    EBISU_CARD: EBISU_CARD_NAME,
    SEIJA_CARD: SEIJA_CARD_NAME,
    CLOWNPIECE_CARD: CLOWNPIECE_CARD_NAME,
    SUIKA_CARD: SUIKA_CARD_NAME,
    TEACUP_REIMU_CARD: TEACUP_REIMU_CARD_NAME,
    TEACUP_MARISA_CARD: TEACUP_MARISA_CARD_NAME
}

# Ability Cards that can never show up in the Permanent Card Shop.
ABILITY_CARD_CANNOT_EQUIP = [
    NAZRIN_CARD_1, NAZRIN_CARD_2
]

STAGE_EXCLUSIVE_CARD_LIST = {
    TUTORIAL_NAME: [REIMU_CARD_1, MARISA_CARD_1, KANAKO_CARD, NITORI_CARD, YUKARI_CARD],
    STAGE1_NAME: [MIKE_CARD, MINORIKO_CARD, ETERNITY_CARD, NEMUNO_CARD],
    STAGE2_NAME: [CIRNO_CARD, WAKASAGI_CARD, SEKIBANKI_CARD, URUMI_CARD],
    STAGE3_NAME: [EBISU_CARD, KUTAKA_CARD, NARUMI_CARD, KOMACHI_CARD],
    STAGE4_NAME: [SANAE_CARD_2, SAKUYA_CARD_2, YOUMU_CARD_2, REIMU_CARD_2, NITORI_STORY_CARD],
    STAGE5_NAME: [TSUKASA_CARD, MEGUMU_CARD, CLOWNPIECE_CARD, TENSHI_THROW_CARD],
    STAGE6_NAME: [SUIKA_CARD, MAMIZOU_CARD, MOMOYO_CARD, SAKI_POWER_CARD, TAKANE_STORY_CARD],
    ENDSTAGE_NAME: [BLANK_CARD, TEACUP_REIMU_CARD, TEACUP_MARISA_CARD]
}

# The following do not include the cards listed above.
# Cards that show up in practically all stages.
STAGE_COMMON_CARD_LIST = [FLANDRE_CARD, FUTO_CARD, AYA_CARD, LIFE_CARD, PATCHOULI_CARD, RINGO_CARD, BYAKUREN_CARD, AUNN_CARD]
# Cards that don't appear in Stage 5 or End of Market.
# Lily White's card actually shows up in Stage 5 See Rules.py.
STAGE1_CARD_LIST = [KOISHI_CARD, STAR_SAPPHIRE_CARD, LUNA_CHILD_CARD, SUNNY_MILK_CARD, TEWI_CARD, RAIKO_CARD, EIRIN_CARD, SUMIREKO_CARD]
# Like the above but Stage 2 onwards.
# Doremy's card actually shows up in Stage 5. See Rules.py.
STAGE2_CARD_LIST = [TAKANE_CARD, SUWAKO_CARD, YUYUKO_CARD, YOUMU_CARD_1, KAGUYA_CARD, SEIJA_CARD, SAKUYA_CARD_1, ALICE_CARD]
# Like the above but Stage 3 onwards.
STAGE3_CARD_LIST = [UFO_CARD, OKINA_CARD, SANNYO_CARD, TENSHI_SHIELD_CARD, SAKI_BIGSHOT_CARD, EIKI_CARD, KEIKI_CARD, TORAMARU_CARD, SEIRAN_CARD]
# These cards appear only in Stage 4 onwards, except End of Market.
LATEGAME_CARD_LIST = [MISUMARU_CARD, MIKO_CARD, MAYUMI_CARD, JOON_CARD, SHION_CARD, JUNKO_CARD, YACHIE_CARD, MARISA_CARD_2, MOON_CARD, MOKOU_CARD, SANAE_CARD_1, UTSUHO_CARD, REMILIA_CARD]

LOW_SKILL_CARD_LIST = [EIRIN_CARD_NAME, KAGUYA_CARD_NAME, MIKO_CARD_NAME, SHION_CARD_NAME, MOMOYO_CARD_NAME, EIKI_CARD_NAME]